version: '2'

services:
  app:
    image: tornadocash/event-monitoring
    environment:
      RPC_URL: https://mainnet.infura.io/v3/...
      ADDRESS: 0x46226040037A0A5bf059e2e1Dc3dc97Ef653743C
      EVENT_SIGNATURE: DepositData(address,bytes32,uint256,uint256)
      ERROR_MESSAGE: Custom error message
      BLOCK_INTERVAL: 1000 # How far back to look for the event
      CRON_EXPRESSION: 0 30 0 * * *
      TELEGRAM_BOT_TOKEN:
      TELEGRAM_CHAT_ID:


